### ISSUE TITLE
Inconsistency between fees_response_schema and documentation

### ISSUE THREAD

**Issue by AusIV** [0xProject/json-schemas#6]
The fees_response_schema [here](https://github.com/0xProject/json-schemas/blob/master/schemas/relayer_api_fees_response_schema.ts) indicates a "feesRecipient" value, while the documentation [here](https://github.com/0xProject/standard-relayer-api) "feeRecipient" value.

Which is correct? I'm assuming "feeRecipient", as that is consistent with other APIs.

**Comment by fabioberger** [comment]
Thanks for the heads up @AusIV! The schema has been updated and re-published to use `feeRecipient` in V0.6.1.
